### ISSUE TITLE
gdown not responding well...

### ISSUE THREAD

**Issue by MonoDin0** [hanselch/server-installer#1]
for some reason I am getting an error saying the google drive is not accessed...

then gave me the error code that freaked me out.

Access denied with the following error:
    cannot retrieve files, you need to add 'Anyone to the link' to access it.

when i check on the link, it's working properly to download the file.

**Comment by hanselch** [comment]
Have you tried updating the `gdown` file?

**Comment by MonoDin0** [comment]
i dont think so... wait, how do i know what version i have?

**Comment by hanselch** [comment]
go to your command prompt and enter:
`py -m pip show gdown`

**Comment by MonoDin0** [comment]
```
Name: gdown                                                                                                             
Version: 4.2.0
Summary: Google Drive Public File/Folder Downloader                                                                     
Home-page: https://github.com/wkentaro/gdown                                                                            
Author:                                                                                                                 
Author-email: Kentaro Wada <www.kentaro.wada@gmail.com>                                                                 
License: MIT                                                                                                            
Location: C:\Users\anime\AppData\Local\Programs\Python\Python312\Lib\site-packages                                      
Requires: beautifulsoup4, filelock, requests, tqdm                                                                      
Required-by:       
```

**Comment by hanselch** [comment]
huh, so it looks like your running version `4.2.0` (ngl this is a first).

what you need to do is update the package. keeping the command prompt open, do `py -m pip install gdown --upgrade` and you will get the latest release!

**Comment by MonoDin0** [comment]
yay! it works!

**Comment by hanselch** [comment]
perfect! need to add a note to program to get a specific version...
